name: NASA PROJECT CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install Server Packages
        run: npm run install-server
      - name: Install Client Packages
        run: npm run install-client
      - name: Install Main Directory Packages
        run: npm install
      - name: Running all the test
        run: npm run test
      - name: Building the client
        run: npm run build --prefix client
